---
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: checkout the code
        uses: actions/checkout@v3
      - name: install go
        uses: actions/setup-go@v3
        with:
          go-version: '1.20.1'
      - name: run unit tests
        run: make test
      - name: build a local artifact
        run: make build
