---
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: checkout the code
        uses: actions/checkout@v4
      - name: install go
        uses: actions/setup-go@v5
        with:
          go-version: '1.20.1'
      - name: Install Task
        uses: arduino/setup-task@v1
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: run unit tests
        run: task test
      - name: build a local artifact
        run: task build
